namespace ProjectMT.Tools.FeelPreview
{
    /// <summary>연구실 상세 패널에 표시할 효과별 역할 설명이다.</summary>
    public sealed partial class CombatFeelCatalogPreviewLab
    {
        private static string DemoExplanation(string typeName) => typeName switch
        {
            "MMF_AnimationCrossfade" => "현재 Animator 상태에서 지정 상태로 부드럽게 섞어 전환합니다.",
            "MMF_Animation" => "Animator Trigger·Bool·Int·Float 파라미터를 변경해 상태 전이를 일으킵니다.",
            "MMF_AnimatorPlayState" => "지정 Animator 상태를 지정한 정규화 시점부터 즉시 재생합니다.",
            "MMF_AnimatorSpeed" => "Animator 재생 속도를 즉시 또는 커브로 변화시켰다가 복구합니다.",
            "MMF_SpriteSheetAnimation" => "스프라이트 목록을 프레임 속도에 맞춰 순서대로 교체 재생합니다.",
            "MMF_Flicker" => "Renderer 색 또는 재질 프로퍼티를 짧은 주기로 반복 점멸시킵니다.",
            "MMF_Material" => "Renderer의 재질 슬롯을 다른 Material로 교체하는 효과입니다.",
            "MMF_MaterialSetProperty" => "현재 Material의 색·Float·Vector 같은 셰이더 값을 직접 변화시킵니다.",
            "MMF_Blink" => "대상 Renderer를 일정 간격으로 켰다 꺼서 모델 자체를 점멸시킵니다.",
            "MMF_ShaderController" => "ShaderController 커브로 디졸브·스캔·발광 같은 셰이더 값을 재생합니다.",
            "MMF_Sprite" => "SpriteRenderer가 표시하는 Sprite 자산을 다른 이미지로 교체합니다.",
            "MMF_SpriteRenderer" => "SpriteRenderer의 색과 X/Y 반전을 시간에 따라 변화시킵니다.",
            "MMF_SpriteRendererAlpha" => "SpriteRenderer의 알파값만 변화시켜 나타남·사라짐을 만듭니다.",
            "MMF_TextureOffset" => "Material 텍스처의 UV Offset을 이동시켜 표면이 흐르는 것처럼 보이게 합니다.",
            "MMF_TextureScale" => "Material 텍스처의 UV Tiling을 변화시켜 무늬를 확대·축소합니다.",
            "MMF_DestinationTransform" => "위치·회전·크기를 하나의 목표 Transform 상태로 함께 이동시킵니다.",
            "MMF_LookAt" => "대상이 지정 위치나 Transform을 바라보도록 회전시킵니다.",
            "MMF_Position" => "Transform을 커브에 따라 지정 거리만큼 이동시킵니다.",
            "MMF_PositionShake" => "Transform 위치에 감쇠하는 고주파 흔들림을 더합니다.",
            "MMF_PositionSpring" => "위치에 충격을 주고 주파수·감쇠값에 따라 탄성 복원시킵니다.",
            "MMF_RotatePositionAround" => "대상 위치를 지정 중심축 주위로 회전 이동시킵니다.",
            "MMF_Rotation" => "Transform 회전을 커브에 따라 절대·가산 방식으로 변화시킵니다.",
            "MMF_RotationShake" => "Transform 회전에 감쇠하는 고주파 흔들림을 더합니다.",
            "MMF_RotationSpring" => "회전에 충격을 주고 주파수·감쇠값에 따라 탄성 복원시킵니다.",
            "MMF_Scale" => "Transform 크기를 커브에 따라 균일 또는 축별로 변화시킵니다.",
            "MMF_ScaleShake" => "Transform 크기에 감쇠하는 고주파 떨림을 더합니다.",
            "MMF_ScaleSpring" => "크기에 충격을 주고 주파수·감쇠값에 따라 탄성 복원시킵니다.",
            "MMF_SetParent" => "대상의 부모 Transform을 바꿔 위치·회전 기준축을 전환합니다.",
            "MMF_SquashAndStretch" => "한 축을 누르거나 늘리면서 다른 축을 반대로 보정합니다.",
            "MMF_SquashAndStretchSpring" => "눌림·늘어남을 Spring 주파수와 감쇠로 탄성 복원시킵니다.",
            "MMF_Wiggle" => "위치·회전·크기 Wiggle 채널을 함께 또는 따로 흔듭니다.",
            "MMF_Light" => "3D Light의 색·광량·범위를 시간 커브로 변화시킵니다.",
            "MMF_Light2D_URP" => "URP 2D Light의 색·광량·반경을 시간 커브로 변화시킵니다.",
            "MMF_ParticlesInstantiation" => "ParticleSystem Prefab을 타격점에 새로 생성해 1회 분출합니다.",
            "MMF_Particles" => "씬에 이미 존재하는 ParticleSystem을 재생·정지·일시정지합니다.",
            "MMF_InstantiateObject" => "지정 Prefab을 위치·회전·크기 조건으로 생성하거나 풀에서 꺼냅니다.",
            "MMF_LineRenderer" => "LineRenderer의 점·폭·색을 변화시켜 선광을 만듭니다.",
            "MMF_TrailRenderer" => "TrailRenderer의 폭·색·잔존시간을 변화시켜 이동 잔상을 만듭니다.",
            "MMF_Fog" => "RenderSettings 안개의 밀도·거리·색을 시간에 따라 변화시킵니다.",
            "MMF_ShaderGlobal" => "전역 Shader Float·Color·Vector·Keyword를 변경해 화면 공통 셰이더에 전달합니다.",
            "MMF_Skybox" => "현재 Skybox Material을 지정 자산 또는 무작위 자산으로 교체합니다.",
            "MMF_CameraShake" => "카메라 위치·회전에 짧고 감쇠하는 흔들림을 전달합니다.",
            "MMF_CameraZoom" => "지정 FOV까지 빠르게 줌인하고 유지한 뒤 원래 시야로 돌아옵니다.",
            "MMF_CameraClippingPlanes" => "카메라 Near·Far Clipping Plane을 변화시켜 렌더 구간을 바꿉니다.",
            "MMF_Fade" => "화면 전체 페이더의 알파를 커브로 올리거나 내려 장면을 가립니다.",
            "MMF_CameraFieldOfView" => "카메라 FOV를 연속 커브로 흔들어 렌즈가 숨 쉬는 듯한 펄스를 만듭니다.",
            "MMF_Flash" => "지정 색과 알파로 화면 전체에 매우 짧은 섬광을 표시합니다.",
            "MMF_CameraOrthographicSize" => "직교 카메라의 Orthographic Size를 변화시켜 화면 배율을 바꿉니다.",
            "MMF_Bloom" => "Legacy Post Processing Bloom의 밝은 영역 번짐 강도를 변화시킵니다.",
            "MMF_Bloom_URP" => "URP Bloom의 밝은 영역 번짐 강도와 임계값을 변화시킵니다.",
            "MMF_ChannelMixer_URP" => "URP RGB 출력 채널에 다른 입력 채널을 섞어 색 관계를 재조합합니다.",
            "MMF_ChromaticAberration" => "Legacy 색수차로 화면 가장자리의 RGB 채널을 벌립니다.",
            "MMF_ChromaticAberration_URP" => "URP 색수차로 화면 가장자리의 RGB 채널을 벌립니다.",
            "MMF_ColorAdjustments_URP" => "URP 노출·대비·채도·색조를 함께 조정합니다.",
            "MMF_ColorGrading" => "Legacy 색보정의 노출·대비·채도·색 필터를 변화시킵니다.",
            "MMF_DepthOfField" => "Legacy 심도 효과로 초점 거리 밖의 화면을 흐리게 합니다.",
            "MMF_DepthOfField_URP" => "URP 심도 효과로 초점 거리 밖의 화면을 흐리게 합니다.",
            "MMF_FilmGrain_URP" => "URP Film Grain 입자를 화면 전체에 더해 거친 질감을 만듭니다.",
            "MMF_GlobalPPVolumeAutoBlend" => "Legacy 전역 Post Process Volume 가중치를 커브로 블렌드합니다.",
            "MMF_GlobalPPVolumeAutoBlend_URP" => "URP 전역 Volume의 여러 효과 가중치를 함께 블렌드합니다.",
            "MMF_LensDistortion" => "Legacy 렌즈 왜곡으로 화면 중심에서 볼록·오목하게 휘게 합니다.",
            "MMF_LensDistortion_URP" => "URP 렌즈 왜곡으로 화면 중심에서 볼록·오목하게 휘게 합니다.",
            "MMF_MotionBlur_URP" => "URP Motion Blur로 움직이는 카메라와 물체에 방향성 잔상을 더합니다.",
            "MMF_PaniniProjection_URP" => "URP Panini Projection으로 넓은 FOV의 가장자리 왜곡을 재투영합니다.",
            "MMF_PPMovingFilter" => "Post Process 필터 영역을 화면 위로 이동시키며 On·Off 전환합니다.",
            "MMF_Vignette" => "Legacy Vignette로 화면 가장자리를 지정 색으로 어둡게 만듭니다.",
            "MMF_Vignette_URP" => "URP Vignette로 화면 가장자리를 지정 색으로 어둡게 만듭니다.",
            "MMF_WhiteBalance_URP" => "URP 색온도와 색조를 바꿔 화면을 따뜻하거나 차갑게 만듭니다.",
            "MMF_FreezeFrame" => "매우 짧게 TimeScale을 0으로 만들어 단일 타격 프레임을 고정합니다.",
            "MMF_TimescaleModifier" => "TimeScale을 지정 배율로 낮추거나 올린 뒤 원래 속도로 복구합니다.",
            _ => "공식 FEEL 데모의 역할을 연구실 대상과 카메라에서 단독 재생합니다."
        };
    }
}
